#!/usr/bin/env node
var ejs = require('ejs')
var fs = require('fs')

if (process.argv.length !== 4) {
  console.log('ejs: <JSON> <TEMPLATE>')
  process.exit()
}

var json = JSON.parse(fs.readFileSync(process.argv[2]))
var template = fs.readFileSync(process.argv[3], 'utf8')
console.log(ejs.render(template, json))
